name: lao_instrument_classifier
description: A Flutter app for classifying Lao musical instruments with unknown detection.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # TensorFlow Lite
  tflite_flutter: ^0.11.0
  
  # Audio recording and playback
  record: ^4.4.4
  just_audio: ^0.9.30
  
  # Audio processing
  fftea: ^1.3.0  # For FFT computation
  
  # State management
  provider: ^6.0.5
  
  # UI components
  flutter_spinkit: ^5.1.0
  percent_indicator: ^4.2.2
  
  # Permissions
  permission_handler: ^11.4.0
  
  # Utilities
  path_provider: ^2.0.11
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/model/
    - assets/images/
    - assets/test_audio/